name: Sync and Deploy content to Pages
on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/folio-org/folio-helm-v2.git
      
      - name: Fetch Upstream Changes
        run: git fetch upstream
      
      - name: Merge Upstream into Fork
        run: |
          git config merge.ours.driver true
          git merge upstream/master --allow-unrelated-histories

      - name: Package Helm Charts
        run: |
          for d in ./charts/*/ ; do
            if [ "$d" == "./charts/platform-core/" ]; then
              continue
            fi
            echo "Building and packaging chart in directory: $d"
            helm dependency build "$d"
            helm package "$d" -d packaged_charts
          done
      
      - name: Index charts
        run: helm repo index . --url https://sul-dlss.github.io/${{ github.event.repository.name }}/
      
      - name: Add and Commit packaged charts and index
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "GitHub Actions"
          git add packaged_charts
          git add index.yaml
          git commit -m "Adding packaged charts and updated index"

      - name: Push packaged charts and index
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
